version: '3.8'

services:
  app:
    build: 
      context: ../PROXY
      dockerfile: ../PROXY/Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16-bullseye
    # volumes:
    #   - ..:/workspace:cached      
    # Overrides default command so things don't shut down after the process ends.
    command: bash -c "cd workspace/ && npm start"
    networks:
      testing_net:
        ipv4_address: 192.10.1.1
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    #network_mode: service:db
  forum: 
    build:
      context: ../FORUM
      dockerfile: ../FORUM/Dockerfile
      args:
        VARIANT: 16-bullseye
    command: bash -c "cd workspace/ && npm start"
    networks:
      testing_net:
        ipv4_address: 192.10.1.3
  auth: 
    build:
      context: ../AUTH
      dockerfile: ../AUTH/Dockerfile
      args:
        VARIANT: 16-bullseye
    command: bash -c "cd workspace/ && npm start"
    networks:
      testing_net:
        ipv4_address: 192.10.1.4
  news:
    build:
      context: ../NEWS
      dockerfile: ../NEWS/Dockerfile
      args:
        VARIANT: 16-bullseye

    command: bash -c "cd workspace/ && npm start"
    # network_mode: host
    networks:
      testing_net:
        ipv4_address: 192.10.1.5
    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data    
    networks:
      testing_net:
        ipv4_address: 192.10.1.2
    

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.1
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@user.com"
      PGADMIN_DEFAULT_PASSWORD: "0000"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      testing_net:
        ipv4_address: 192.10.1.15
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 192.10.0.0/16
